### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/level-up#3]
- [x] Fonts not loading

- [x] THe Menu is not opening

- [x] why doesn't the .post-img load

- [x] Comments not loading in Page

- [x] if plugin already exists, then the activation link should be normal one.

- [x] ampforwp-welcome-page  needs to change as per the template mode

- [x] options loading in the frontend causing validation such as amp-animation

- [x] Search not working in footer

- [x] Add theme support

- [x] menus / widgets of the amp plugin should not load in template mode

- [ ] need to remove AMP customizer https://monosnap.com/file/rBCMJ3eHhjSIoc8Jgr2G3eXBooDYES

- [ ] Need to remove View AMP from everywhere and https://monosnap.com/file/AAfjqrydPGsxw9bdO3VOjpnVoB7Vpu

- [ ] Template Mode Activated - should be displayed here: https://monosnap.com/file/Zl1FjpinlZibftKubwCYEecrYkjQXU

FRONTEND
- [ ] loop flex fix

**Comment by ajeetku** [comment]
` Comments not loading in Page` already working
